/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PassTimingRouteImport } from './routes/pass-timing'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as FoodChoiceRouteImport } from './routes/food-choice'
import { Route as EmergencyRequestRouteImport } from './routes/emergency-request'
import { Route as IndexRouteImport } from './routes/index'

const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassTimingRoute = PassTimingRouteImport.update({
  id: '/pass-timing',
  path: '/pass-timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodChoiceRoute = FoodChoiceRouteImport.update({
  id: '/food-choice',
  path: '/food-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRequestRoute = EmergencyRequestRouteImport.update({
  id: '/emergency-request',
  path: '/emergency-request',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emergency-request': typeof EmergencyRequestRoute
  '/food-choice': typeof FoodChoiceRoute
  '/manage': typeof ManageRoute
  '/pass-timing': typeof PassTimingRoute
  '/profile': typeof ProfileRoute
  '/request': typeof RequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emergency-request': typeof EmergencyRequestRoute
  '/food-choice': typeof FoodChoiceRoute
  '/manage': typeof ManageRoute
  '/pass-timing': typeof PassTimingRoute
  '/profile': typeof ProfileRoute
  '/request': typeof RequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emergency-request': typeof EmergencyRequestRoute
  '/food-choice': typeof FoodChoiceRoute
  '/manage': typeof ManageRoute
  '/pass-timing': typeof PassTimingRoute
  '/profile': typeof ProfileRoute
  '/request': typeof RequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emergency-request'
    | '/food-choice'
    | '/manage'
    | '/pass-timing'
    | '/profile'
    | '/request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emergency-request'
    | '/food-choice'
    | '/manage'
    | '/pass-timing'
    | '/profile'
    | '/request'
  id:
    | '__root__'
    | '/'
    | '/emergency-request'
    | '/food-choice'
    | '/manage'
    | '/pass-timing'
    | '/profile'
    | '/request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmergencyRequestRoute: typeof EmergencyRequestRoute
  FoodChoiceRoute: typeof FoodChoiceRoute
  ManageRoute: typeof ManageRoute
  PassTimingRoute: typeof PassTimingRoute
  ProfileRoute: typeof ProfileRoute
  RequestRoute: typeof RequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass-timing': {
      id: '/pass-timing'
      path: '/pass-timing'
      fullPath: '/pass-timing'
      preLoaderRoute: typeof PassTimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-choice': {
      id: '/food-choice'
      path: '/food-choice'
      fullPath: '/food-choice'
      preLoaderRoute: typeof FoodChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-request': {
      id: '/emergency-request'
      path: '/emergency-request'
      fullPath: '/emergency-request'
      preLoaderRoute: typeof EmergencyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmergencyRequestRoute: EmergencyRequestRoute,
  FoodChoiceRoute: FoodChoiceRoute,
  ManageRoute: ManageRoute,
  PassTimingRoute: PassTimingRoute,
  ProfileRoute: ProfileRoute,
  RequestRoute: RequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
